site_name: 数学分析习题项目
site_url: https://monohunter.github.io/cgmpedia/
site_description: 中科大《数学分析》第2版习题解答、精选证明与延伸思考

theme:
  name: material
  # custom_dir: overrides
  font: false
  icon:
    logo: material/math-integral-box
  language: zh
  palette:
  # 浅色模式配置
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    # 深色模式配置
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

  features:
    #- navigation.tabs
    - navigation.top
    - navigation.expand
    - search.highlight

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - glightbox
  - search:
      lang: [en, ja]          # 中文一定要加
      separator: '[\s\-\.]+'  # 优化中文切词

extra_javascript:
  - javascripts/mathjax.js
  # 固定版本，避免 @3 自动变化；仍依赖 jsDelivr 网络。
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/katex.js  # 我们下一步要创建的初始化脚本
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

copyright: "Copyright &copy; 2026 Yangxin Zhang | 持续接受勘误与讨论"

extra:
  generator: false